### Server Configuration
server:
  port: 6100
  address: 172.30.1.19
### Spring Boot Configuration
spring:
  application.name: gateway
  ### Spring Cloud Configuration
  cloud:
    gateway:
      ### Define Global Filters
      default-filters:
        - name: GlobalFilter
          args:
            usage: LOGGING
      ### Define MicroService that Routing
      routes:
        ### Account API
        - id: account-api
          uri: http://221.156.195.73:6101/
          predicates:
            - Path=/api/v1/account/**
          filters:
            - name: AccountAPILogger
              args:
                usage: LOGGING
        ### Schedule API
        - id: schedule-api
          uri: http://221.156.195.73:6102/
          predicates:
            - Path=/api/v1/schedule/**
          filters:
            - name: ScheduleAPILogger
              args:
                usage: LOGGING
springdoc:
  swagger-ui:
    urls:
      - name: account-api
        url: /v3/api-docs/account-api
      - name: schedule-api
        url: /v3/api-docs/schedule-api