server:
  address: 172.30.1.19
  port: 6101
spring:
  application.name: account-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sogonsogon0129@
    url: jdbc:mysql://localhost:3306/scpr_account_api
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://172.30.1.19:6111/eureka
  instance:
    hostname: 172.30.1.19