server:
  address: 172.30.1.19
  port: 6101
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sogonsogon0129@
    url: jdbc:mysql://localhost:3306/scpr_account_api
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect