server:
  address: 172.30.1.19
  port: 6102
  shutdown: graceful
springdoc:
  api-docs:
    path: /schedule-api/docs
spring:
  application.name: schedule-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sogonsogon0129@
    url: jdbc:mysql://localhost:3306/scpr_schedule_api
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.30.1.19:6111/eureka
  instance:
    hostname: 172.30.1.19